services:

  db:
    image: postgres:15.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: "${DOCKERHUB_USERNAME}/${PROJECT_NAME}"
    restart: always
    depends_on: 
      - db
    volumes:
      - static_value:/app/static/  
      - media_value:/app/media/      
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    depends_on:
      - web 
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/  
      - media_value:/var/html/media/      

volumes:
  postgres_data: 
  static_value:  
  media_value: 
